Hello World Programs/HelloWorld.js
I just added hello world in my favorite programming language JavaScript. Cheers to open source!
=> added hello world program in javascript

Algorithms/IsPrime.py
Algorithm that answer if numer is prime.
=> Create IsPrime Algorithm

Hello World Programs/hello_world.c
=> C code for hello world and hello hactoberfest

Java programs/frequency_of_char.java
added frequency of character program in java
=> add frequency of char program in java

Java programs/README.md, Java programs/longest_common_subsequence.java
Hey @Mustafiz04 , I just added [Longest Common Subsequence](https://www.geeksforgeeks.org/longest-common-subsequence-dp-4/) in Java programs section. I also created a README for the same folder. Hope you like my contribution!
=> Added LCS in Java programs

Hello World Programs/SQL
Added code in SQL, please add Hacktober-accepted lebel to my PR.
=> Created in SQL

Java programs/README.md, Java programs/frequency_of_char.java, Java programs/longest_pallindromic_subsequence.java
Hey @Mustafiz04 , I just added Longest Palindromic Subsequence ( A must-known variation of LCS ) in Java programs section. I also fixed frequency of characters programs.
=> Added LPS and fixed Freq Of Chars in Java programs

Algorithms/doubly-linked-list.cpp, Algorithms/linked-list.cpp
Added a c++ file containing the implementation of a singly linked list.
=> adding a file of singly linked list to the folder in c++ code

Projects/sample_calculator/calculator.html
hey there,
I have added a simple calculator.
=> Add simple calculator

Algorithms/DynamicProgramming/README.md, Algorithms/DynamicProgramming/zero_one_knapsack.java
I added [0-1 knapsack problem](https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/) in the dynamic programming section! Hope you like my contribution!
=> added recursive zero one knapsack

Games/mainsnake.cpp, vector implementation.cpp
This is my own personal implementation of a vector. It works better than the STL c++ vector class.
=> Inserted a cpp file

Algorithms/SortingAlgo/MergeSort.cpp
Added Merge Sort Algo Implementation in CPP.
Peace ✌️
=> Merge Sort Algorithm

Algorithms/patterns.cpp
This c++ files contain 7 pattern implementations using for loops, switch case  and conditional statements.
=> added a c++ file via upload

Algorithms/SortingAlgo/README.md, Algorithms/SortingAlgo/insertion_Sort.cpp, Algorithms/SortingAlgo/selection_sort.java
Hey @Mustafiz04 , I added [Selection sort](https://en.wikipedia.org/wiki/Selection_sort) to your awesome repo. Also, I edited the README of the Sorting Algorithm section so that everyone gets a better idea! I also optimized insertion sort code!
=> Added Selection Sort in Java and fixed insertion sort swapping

Data Structure/Stack/postfix_expression_using_stack.cpp
Added code to solve post fix expression using stack for #2
=> solving post-fix expression using stack

Algorithms/SearchingALgo/Depth_First_Search.cpp
Depth First Search is one of the main graph algorithms.
Depth First Search finds the lexicographical first path in the graph from a source vertex u to each vertex. Depth First Search will also find the shortest paths in a tree (because there only exists one simple path), but on general graphs this is not the case.
The algorithm works in O(m+n) time where n is the number of vertices and m is the number of edges.
=> Depth First Search

Algorithms/DynamicProgramming/DP_Broken_Profile.cpp
Dynamic Programming on Broken Profile. Problem "Parquet"
=> DP_Broken_Profile

Java programs/fibonacci.java
This program displays the nth Fibonacci number. Both top-bottom(memoization) and bottom-up methods in Dynamic programming are used in this program.
=> Fibonacci program using Dynamic Programming

Algorithms/Recurssion/factorials.js
I added factorial.js in Algorithms/Recurssion. It contains a function that counts the factorial of the input parameter.
Tthank You.
=> added factorial algorithm in js

Hello World Programs/hello_world.rs, Hello World Programs/hello_world.ts
HelloWorld for Rust and TypeScript
=> added hello_world for rust and typescript

Data Structure/armstrong.cpp, Data Structure/binary.cpp, Data Structure/insert a node at nth pos.cpp, Data Structure/reverse with blocks.cpp
Merge this fast. My 4th pull request.
=> Adding four files via upload

Data Structure/Array/MatrixMultiplication.c
@Mustafiz04 I have contributed by adding Matrix Multiplication in C. Check it out and if everything is fine please merge it.
=> Added Matrix Multiplication in C

EXCEL_SQL
The connection string for SQL query in Excel database using Macros
=> connection Excel_SQL

Algorithms/Backtracking/NQueen_Problem.cpp
Added the code for the famous N Queen Backtracking Problem in the most optimized way using C++!
=> Added N Queen Backtracking Problem in CPP

Algorithms/Recurssion/Fibonacci.c
@Mustafiz04 I have added Fibonacci series using recursion in C. Check it out and if everything is fine please merge it.
=> Added Fibonacci series in C

Data Structure/Array/binarysearchinredundantarray.c, Data Structure/Array/quicksort.c, Data Structure/LinkedList/dllusingc.c, Data Structure/Stack/rev.c, Data Structure/Stack/stackusingarray.c, Data Structure/Stack/stackwithLinkedLIST.c
Hi I saw your Instagram Post. So I thought I could commit some codes to this repo. Hope you will accept it.
=> hactoberfestcommit

Algorithms/Recurssion/palindrome number.cpp
Checking for the palindrome number using a recursive function.
=> Create  palindrome number.cpp

Algorithms/AllUniquePaths.java
Java program to find total number of unique path from top left to bottom right in MxN matrix.
=> All unique path in java

Algorithms/README.md, Data Structure/README.md, Games/README.md, Hello World Programs/README.md, Java programs/README.md, Machine Learning Projects/README.md, Projects/README.md
Making the README.md file worthwhile to check
=> Updating README s In folders

Projects/Contact Management System/Readme.md, Projects/Contact Management System/main.cpp
This a simple C++ Console application that is used to manage and store the contacts of the user.
=> Added the Contact Management System

Algorithms/SortingAlgo/radix_sort.c
In this program the given array is sorted using radix sort algorithm.
=> created radix sort

queue using linked list
=> Create queue using linked list

Hello World Programs/README.md, Hello World Programs/hello_world.matlab
add hello world with matlab programming
=> add matlab programming

Games/tictactoe.cpp
easy tic-tac-toe program. Enjoy coding!!
=> tictactoe.cpp

Projects/Signle Neuron Implementation/Red or Blue Flower/Neuron.py, Projects/Signle Neuron Implementation/Red or Blue Flower/README.txt
Program trains a single Neuron to tell whether a Flower is Blue or Red based on the petal size entered. This is basic implementation of the most simplest type of Neuron.
=> A single Python Project that show implementation of a single neuron

Hello World Programs/README.md
I added the checkbox for languages that existed scripts but were not listed
=> Adding missing Checks

Algorithms/sum of n natural number.java
=> sum of n natural number

square number sum.java
square number sum java program
=> square number sum java program

Data Structure/Array/insertion_sort.c
#2 
Added insertion sort program in c language
=> added insertion sort program in c language.

Hello World Programs/HelloWorld.pas, Java programs/HeapSort.java
Hello,
I add file HeapSort.java and HelloWorld.pas
Contribute for HacktoberFest2020
thx
=> Contribute for HacktoberFest2020

pangrams-prog.java, weight.java
hey, weights program is a new contribution\...the pangrams program i guess got comitted again and i cannot remove it . please accept my request
=> weights java

Projects/C++/Bus Ticket Reservation System.cpp
In this project, I have tried making a bus ticket reservation system in C++ language using the concept of pointers, object oriented programming (OOP) and data file handling.
=> Added a project named Bus Ticket Reservation System.cpp in C++ projects folder

Algorithms/SortingAlgo/PigeonholeSort.cpp, Projects/javascript todo app/main.html, Projects/javascript todo app/todo.css, Projects/javascript todo app/todo.js
issue no - #2 
added in sorting folder
sorting of an array by pigeonhole algorithm
=> Pigeonhole Sort Algo

Algorithms/SortingAlgo/sortingFunction.java
sorting function program in java
=> sorting function program

Algorithms/Backtracking/permutations of a string.java
permutations of a string java program
=> permutations of a string java program

Data Structure/karprekar.java
karprekar number program in java
=> karprekar number

Algorithms/SearchingALgo/KMP algorithm.java
KMP algo for pattern searching in string java program.
=> KMP algo for pattern searching

Algorithms/README.md, Data Structure/README.md, Games/README.md, Hello World Programs/README.md, Java programs/README.md, Machine Learning Projects/README.md, Projects/README.md
I hope to help with my contribution. Greetings!
=> [fix] url of folders inside github

Projects/C++/monoalphabetic.cpp
Hi.I added code of monoalphabetic cipher.
=> created monoalphabetic.cpp

Projects/Locust/README.md, Projects/Locust/locustfile.py
A working sample of Locust load testing on Github API.
=> Locust Load Testing

Algorithms/DynamicProgramming/LongestCommonSubstring.cpp, Algorithms/DynamicProgramming/LongestPalindromicSubsequence.cpp, Algorithms/DynamicProgramming/README.md
LPS iterative approach and LCS recursive approach using Dynamic Programming.
=> Added the code for LCS and LPS problem using DP

Algorithms/SortingAlgo/rust_bubble_sort.rs
=> Adding Rust Bubble Sort

Algorithms/Stcak.py
=> Stack in Python

Games/MineSweeper.cpp
=> MineSweeper game

Java programs/Average.java
A simple Java program that gets the average of a group of numbers.
=> Added Average.java

Games/MasterMing.cpp
A simple command line c++ game to increase your memory power.
=> MasterMing game added

Data Structure/Linked List Reversal
=> Create Linked List Reversal

Data Structure/BinarySearchTree/lowest common ancestor.cpp
Finds the Lowest Common Ancestor of two nodes of BST that have values n1 and n2
=> Create lowest common ancestor.cpp

Data Structure/BinaryTree/Balanced binary tree, Data Structure/BinaryTree/Same Tree, Data Structure/BinaryTree/Symmetric Tree
Please have a look of the codes and please merge it.
=> Added the codes for Symmetric tree , same tree and balanced binary tree in C++.
